{% extends "layout.phtml" %}

{% block content %} 
<div class="container-fluid">
    <div class="row">
        {% include "menu.phtml" with {'base_url': base_url} %}
        <div class="col-md-10 mt-3 portfolio">
            <div class="container-fluid">
                <div class="row">
                    {% for filename in contents %}
                    <div class="col-md-4 images">
                        <img class="d-block img-fluid img-responsive " src={{ "images/auto/" ~ filename }} ></img>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} 