{% extends "layout.phtml" %}

{% block content %} 

<div class="container-fluid">
    <div class="row">
        <div id="carouselControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
                {% for filename in contents %}
                    <div class="carousel-item">
                        <img class="d-block img-fluid img-responsive col-xs-12" src={{ "images/homepage/" ~ filename }} ></img>
                    </div>
                {% endfor %}
            <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('img').bind("contextmenu",function(e){
       e.preventDefault();
    }); 
</script>
{% endblock %}