<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        
        <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="css/main.css" />

        <script type="text/javascript" src="js/tether.min.js"></script>
        <script type="text/javascript" src="js/jquery-3.1.1.min.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>

        <script type="text/javascript"  src="js/scripts.js"></script>

    </head>
    <body>

        {% block content %} {% endblock %}
    </body>
</html>
