<div class="col-md-2 menu pr-3">

    <div class="bootstrap-vertical-nav">

        <button class="btn  hidden-md-up collapsed" type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class=""></span>
        </button>
        <a class="navbar-brand mb-3" href="{{ base_url ~ 'home' }}"><img class="img-responsive" src="images/sample-logo.png" /></a>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav flex-column" id="exCollapsingNavbar3">
                
                <li class="nav-item">
                    <a class="nav-link text-xs-center text-md-left" href="{{ base_url ~ 'auto' }}">Auto/Moto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-xs-center text-md-left" href="{{ base_url ~ 'fashion' }}">Fashion/Glam</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-xs-center text-md-left" href="{{ base_url ~ 'about' }}">About</a>
                </li>
            </ul>
        </div>

    </div>
</div>